[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "/"
  command = "npm run build"

[context.production]
  environment = { REACT_APP_API_HOST = "/api/" }

[[redirects]]
  from = "/api/*"
  to = "https://api.example.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
